### ISSUE TITLE
Implement AddClub

### ISSUE THREAD

**Issue by julianki-cs** [cl-uh-b/cl-uh-b#13]
Please do work for this task in a branch named issue-13. 

In AddClub, please make:
* Name required (req.)
* Type of club req.
* Email req.
* Contact req.
* Description optional
* Image Optional

Instead of a direct add, implement add so that goes to the admins for review.

**Comment by tiffanywilliams** [comment]
We should probably make a page for the super-admins that shows them the club submissions. From the page, they could accept or deny the club. If accept, then the club will show up in the browsery. If deny, then the admin will have to fill out a field describing why the club was deny, which will be sent to the submitter's email.
